// Generated by https://quicktype.io

class BackdropImageDAO {
  double aspectRatio;
  String filePath;
  int height;
  dynamic iso6391;
  double voteAverage;
  int voteCount;
  int width;

  BackdropImageDAO({
    this.aspectRatio,
    this.filePath,
    this.height,
    this.iso6391,
    this.voteAverage,
    this.voteCount,
    this.width,
  });

  factory BackdropImageDAO.fromJSON(Map<String, dynamic> map){ 
    return BackdropImageDAO(
      aspectRatio: map['aspect_ratio'],
      filePath: map['file_path'] ,
      height: map['height'],
      width: map['width'],
      iso6391: map['iso_639_1'],
      voteAverage: map['vote_average'],
      voteCount: map['vote_count'],
    );
  }
}
