// Generated by https://quicktype.io

class VideoDAO {
  String id;
  String iso6391;
  String iso31661;
  String key;
  String name;
  String site;
  int size;
  String type;

  VideoDAO({
    this.id,
    this.iso6391,
    this.iso31661,
    this.key,
    this.name,
    this.site,
    this.size,
    this.type,
  });

  factory VideoDAO.fromJSON(Map<String, dynamic> map){ //Recibe json convertido a mapa
    return VideoDAO(
      name: map['name'],
      id: map['id'] ,
      key: map['key'],
      site: map['site'],
      size: map['size'],
      type: map['type'],
    );
  }
}
